import { readFile, writeFile } from 'node:fs/promises';
import { join, resolve } from 'node:path';
import { pathToFileURL } from 'node:url';
import { loadConfig } from '../config.js';
import type { ComponentsSimilarity, SimilarityCluster, SimilarityPair } from './types.js';

export const COMPONENTS_COMMENT_MARKER = '<!-- visual-regression-ci:components -->';

function pct(score: number): string {
  return `${Math.round(score * 100)}%`;
}

function clusterSection(cluster: SimilarityCluster, allPairs: SimilarityPair[]): string {
  const memberSet = new Set(cluster.members);
  const clusterPairs = allPairs
    .filter((p) => memberSet.has(p.nameA) && memberSet.has(p.nameB))
    .slice(0, 5);

  const rows = cluster.members.map((m) => {
    const bold = m === cluster.representative ? `**${m}** _(representative)_` : m;
    return `| ${bold} |`;
  });

  const pairRows = clusterPairs.map((p) => `| \`${p.nameA}\` ↔ \`${p.nameB}\` | ${pct(p.score)} |`);

  return [
    `#### Cluster · avg similarity ${pct(cluster.avgScore)}`,
    '',
    '| Component |',
    '|-----------|',
    rows.join('\n'),
    '',
    `> **Suggestion:** ${cluster.suggestion}`,
    '',
    pairRows.length
      ? `<details><summary>Top similar pairs</summary>\n\n| Pair | Score |\n|------|-------|\n${pairRows.join('\n')}\n\n</details>`
      : '',
  ]
    .filter((l) => l !== undefined)
    .join('\n');
}

export function buildComponentsMarkdown(data: ComponentsSimilarity): string {
  const { clusters, pairs, totalComponents, threshold } = data;

  const headerLine =
    clusters.length === 0
      ? `### 🧩 Component Similarity — no duplicates detected\n\nAll ${totalComponents} scanned components are sufficiently distinct (threshold: ${pct(threshold)}).`
      : `### 🧩 Component Similarity — ${pairs.length} similar pair${pairs.length === 1 ? '' : 's'} found\n\n${clusters.length} cluster${clusters.length === 1 ? '' : 's'} across ${totalComponents} components may be candidates for consolidation.`;

  const parts: string[] = [COMPONENTS_COMMENT_MARKER, headerLine];

  if (clusters.length > 0) {
    parts.push('---');
    for (const cluster of clusters) {
      parts.push(clusterSection(cluster, pairs));
    }
  }

  parts.push(`<sub>Analyzed ${totalComponents} components · threshold ${pct(threshold)} · Generated by visual-regression-ci</sub>`);
  return parts.join('\n\n');
}

export async function report(configPath?: string): Promise<ComponentsSimilarity> {
  const config = await loadConfig(configPath);
  const outDir = resolve(process.cwd(), config.outDir);

  const data: ComponentsSimilarity = JSON.parse(
    await readFile(join(outDir, 'components-similarity.json'), 'utf8'),
  );

  const body = buildComponentsMarkdown(data);
  await writeFile(join(outDir, 'components-report.md'), body);
  console.log(`Components report written → out/components-report.md (${data.clusters.length} clusters)`);
  return data;
}

const isMain = process.argv[1] ? import.meta.url === pathToFileURL(process.argv[1]).href : false;
if (isMain) {
  report().catch((err) => { console.error(err); process.exit(1); });
}
