import { readFile, writeFile } from 'node:fs/promises';
import { join, resolve, relative } from 'node:path';
import { loadConfig } from './config.ts';
import type { ClassifiedResult, Verdict } from './classify.ts';

export const COMMENT_MARKER = '<!-- visual-regression-ci -->';

export interface ReportSummary {
  total: number;
  changed: number;
  bugs: number;
  expected: number;
  unreviewed: number;
  added: number;
  removed: number;
}

const VERDICT_BADGE: Record<Verdict, string> = {
  bug: '🐞 **Likely bug**',
  expected: '✅ Expected',
  unreviewed: '❔ Unreviewed',
};

function imageUrl(outDir: string, file: string | undefined, base: string): string | undefined {
  if (!file) return undefined;
  const rel = relative(outDir, resolve(file)).split('\\').join('/');
  if (!base) return rel; // local mode: relative path
  return `${base.replace(/\/$/, '')}/${rel}`;
}

function summarize(results: ClassifiedResult[]): ReportSummary {
  const s: ReportSummary = { total: results.length, changed: 0, bugs: 0, expected: 0, unreviewed: 0, added: 0, removed: 0 };
  for (const r of results) {
    if (r.status === 'added') s.added++;
    else if (r.status === 'removed') s.removed++;
    else if (r.status === 'changed') {
      s.changed++;
      const v = r.classification?.verdict ?? 'unreviewed';
      if (v === 'bug') s.bugs++;
      else if (v === 'expected') s.expected++;
      else s.unreviewed++;
    }
  }
  return s;
}

function header(s: ReportSummary): string {
  if (s.changed === 0 && s.added === 0 && s.removed === 0) {
    return `### 🖼️ Visual Regression — no visual changes detected\n\nAll ${s.total} screens match \`main\`.`;
  }
  const bits: string[] = [];
  if (s.bugs) bits.push(`🐞 **${s.bugs} likely bug${s.bugs > 1 ? 's' : ''}**`);
  if (s.expected) bits.push(`✅ ${s.expected} expected`);
  if (s.unreviewed) bits.push(`❔ ${s.unreviewed} unreviewed`);
  if (s.added) bits.push(`🆕 ${s.added} new`);
  if (s.removed) bits.push(`🗑️ ${s.removed} removed`);
  return `### 🖼️ Visual Regression — ${s.changed} screen${s.changed === 1 ? '' : 's'} changed\n\n${bits.join(' · ')}`;
}

function screenSection(r: ClassifiedResult, outDir: string, base: string): string {
  const baseUrl = imageUrl(outDir, r.baselineFile, base);
  const currUrl = imageUrl(outDir, r.currentFile, base);
  const diffUrl = imageUrl(outDir, r.diffFile, base);

  const verdict = r.classification?.verdict ?? 'unreviewed';
  const title = `${VERDICT_BADGE[verdict]} — \`${r.route}\` @ ${r.viewport}`;
  const meta = r.classification
    ? `<sub>${r.classification.category} · ${r.classification.severity} · ${(r.ratio * 100).toFixed(2)}% changed</sub>\n\n> ${r.classification.reason}`
    : `<sub>${(r.ratio * 100).toFixed(2)}% changed</sub>`;

  const cells: string[] = [];
  const heads: string[] = [];
  if (baseUrl) { heads.push('Baseline (main)'); cells.push(`<img src="${baseUrl}" width="280">`); }
  if (currUrl) { heads.push('Current (PR)'); cells.push(`<img src="${currUrl}" width="280">`); }
  if (diffUrl) { heads.push('Diff'); cells.push(`<img src="${diffUrl}" width="280">`); }

  const table = `<table><tr>${heads.map((h) => `<th>${h}</th>`).join('')}</tr><tr>${cells.map((c) => `<td>${c}</td>`).join('')}</tr></table>`;
  return `#### ${title}\n\n${meta}\n\n${table}`;
}

export function buildMarkdown(results: ClassifiedResult[], outDir: string, base: string): { body: string; summary: ReportSummary } {
  const summary = summarize(results);
  const parts = [COMMENT_MARKER, header(summary)];

  const order: Record<Verdict | 'added' | 'removed', number> = { bug: 0, unreviewed: 1, expected: 2, added: 3, removed: 4 };
  const interesting = results
    .filter((r) => r.status !== 'unchanged')
    .sort((a, b) => {
      const ka = a.status === 'added' || a.status === 'removed' ? a.status : (a.classification?.verdict ?? 'unreviewed');
      const kb = b.status === 'added' || b.status === 'removed' ? b.status : (b.classification?.verdict ?? 'unreviewed');
      return order[ka] - order[kb];
    });

  for (const r of interesting) {
    if (r.status === 'added' || r.status === 'removed') {
      const label = r.status === 'added' ? '🆕 New screen' : '🗑️ Removed screen';
      parts.push(`#### ${label} — \`${r.route}\` @ ${r.viewport}`);
    } else {
      parts.push(screenSection(r, outDir, base));
    }
  }

  parts.push(`<sub>Generated by visual-regression-ci · ${summary.total} screens compared</sub>`);
  return { body: parts.join('\n\n'), summary };
}

export async function report(configPath?: string): Promise<ReportSummary> {
  const config = await loadConfig(configPath);
  const outDir = resolve(process.cwd(), config.outDir);
  const results: ClassifiedResult[] = JSON.parse(await readFile(join(outDir, 'classification.json'), 'utf8'));
  const base = process.env.VRT_IMAGE_BASE_URL ?? '';

  const { body, summary } = buildMarkdown(results, outDir, base);
  await writeFile(join(outDir, 'report.md'), body);
  await writeFile(join(outDir, 'summary.json'), JSON.stringify(summary, null, 2));

  console.log(`Report written to ${join(config.outDir, 'report.md')}`);
  console.log(`Summary: ${summary.bugs} bugs, ${summary.expected} expected, ${summary.unreviewed} unreviewed, ${summary.changed} changed total.`);
  return summary;
}

const isMain = import.meta.url === `file://${process.argv[1]}`;
if (isMain) {
  report()
    .then((summary) => {
      if (process.env.VRT_FAIL_ON_BUG === 'true' && summary.bugs > 0) process.exit(1);
    })
    .catch((err) => {
      console.error(err);
      process.exit(1);
    });
}
